Page({
  data: {
    list: [
      {
        alpha: 'A',
        subItems: [
          { name: '阿坝藏族羌族自治州' },
          { name: '阿克苏地区' },
          { name: '阿拉尔市' },
          { name: '阿拉善盟' },
          { name: '阿勒泰地区' },
        ],
      },
      {
        alpha: 'B',
        subItems: [
          { name: '白城市' },
          { name: '百色市' },
          { name: '白沙黎族自治县' },
          { name: '白山市' },
          { name: '白银市' },
          { name: '巴南区' },
          { name: '宝坻区' },
        ],
      },
      {
        alpha: 'C',
        subItems: [
          { name: '沧州市' },
          { name: '长春市' },
          { name: '常德市' },
          { name: '昌都市' },
          { name: '昌吉回族自治州' },
          { name: '昌江黎族自治县' },
          { name: '长宁区' },
          { name: '昌平区' },
        ],
      },
      {
        alpha: 'D',
        subItems: [
          { name: '大渡口区' },
          { name: '大理白族自治州' },
          { name: '大连市' },
          { name: '丹东市' },
        ],
      },
      {
        alpha: 'E',
        subItems: [{ name: '鄂尔多斯市' }, { name: '恩施土家族苗族自治州' }, { name: '鄂州市' }],
      },
      {
        alpha: 'F',
        subItems: [
          { name: '防城港市' },
          { name: '房山区' },
          { name: '丰都县' },
          { name: '奉节县' },
          { name: '丰台区' },
          { name: '抚州市' },
        ],
      },
      {
        alpha: 'G',
        subItems: [
          { name: '甘南藏族自治州' },
          { name: '赣州市' },
          { name: '甘孜藏族自治州' },
          { name: '高雄市' },
          { name: '广安市' },
        ],
      },
      {
        alpha: 'H',
        subItems: [
          { name: '哈尔滨市' },
          { name: '海北藏族自治州' },
          { name: '海淀区' },
          { name: '海东市' },
          { name: '海口市' },
          { name: '海南藏族自治州' },
          { name: '海西蒙古族藏族自治州' },
          { name: '哈密市' },
          { name: '邯郸市' },
          { name: '杭州市' },
          { name: '呼和浩特市' },
          { name: '惠州市' },
        ],
      },
      {
        alpha: 'J',
        subItems: [
          { name: '嘉定区' },
          { name: '佳木斯市' },
          { name: '吉安市' },
          { name: '江北区' },
          { name: '江津区' },
          { name: '江门市' },
          { name: '焦作市' },
          { name: '嘉兴市' },
          { name: '嘉义市' },
          { name: '嘉义县' },
        ],
      },
      {
        alpha: 'K',
        subItems: [
          { name: '开封市' },
          { name: '开州区' },
          { name: '喀什地区' },
          { name: '可克达拉市' },
          { name: '克拉玛依市' },
          { name: '克孜勒苏柯尔克孜自治州' },
          { name: '葵青区' },
          { name: '昆明市' },
          { name: '昆玉市' },
        ],
      },
      {
        alpha: 'L',
        subItems: [
          { name: '来宾市' },
          { name: '廊坊市' },
          { name: '兰州市' },
          { name: '拉萨市' },
          { name: '乐东黎族自治县' },
          { name: '乐山市' },
          { name: '梁平区' },
          { name: '凉山彝族自治州' },
          { name: '连云港市' },
          { name: '聊城市' },
        ],
      },
      {
        alpha: 'M',
        subItems: [
          { name: '马鞍山市' },
          { name: '茂名市' },
          { name: '眉山市' },
          { name: '梅州市' },
          { name: '门头沟区' },
          { name: '绵阳市' },
          { name: '苗栗县' },
        ],
      },
      {
        alpha: 'N',
        subItems: [
          { name: '南岸区' },
          { name: '南昌市' },
          { name: '南充市' },
          { name: '南川区' },
          { name: '南京市' },
          { name: '南开区' },
          { name: '南宁市' },
        ],
      },
      {
        alpha: 'P',
        subItems: [
          { name: '盘锦市' },
          { name: '攀枝花市' },
          { name: '澎湖县' },
          { name: '彭水苗族土家族自治县' },
          { name: '平顶山市' },
          { name: '屏东县' },
          { name: '平谷区' },
        ],
      },
      {
        alpha: 'Q',
        subItems: [
          { name: '黔东南苗族侗族自治州' },
          { name: '潜江市' },
          { name: '黔江区' },
          { name: '黔南布依族苗族自治州' },
          { name: '黔西南布依族苗族自治州' },
          { name: '綦江区' },
          { name: '青岛市' },
          { name: '青浦区' },
        ],
      },
      {
        alpha: 'R',
        subItems: [{ name: '日喀则市' }, { name: '日照市' }, { name: '荣昌区' }],
      },
      {
        alpha: 'S',
        subItems: [
          { name: '三门峡市' },
          { name: '三明市' },
          { name: '三沙市' },
          { name: '三亚市' },
          { name: '商洛市' },
          { name: '商丘市' },
        ],
      },
      {
        alpha: 'T',
        subItems: [
          { name: '塔城地区' },
          { name: '泰安市' },
          { name: '台北市' },
          { name: '台东县' },
          { name: '台南市' },
          { name: '太原市' },
        ],
      },
      {
        alpha: 'W',
        subItems: [
          { name: '万宁市' },
          { name: '万州区' },
          { name: '湾仔区' },
          { name: '潍坊市' },
          { name: '威海市' },
          { name: '渭南市' },
          { name: '文昌市' },
          { name: '文山壮族苗族自治州' },
          { name: '温州市' },
          { name: '乌海市' },
        ],
      },
      {
        alpha: 'X',
        subItems: [
          { name: '厦门市' },
          { name: '西安市' },
          { name: '湘潭市' },
          { name: '湘西土家族苗族自治州' },
          { name: '襄阳市' },
          { name: '咸宁市' },
          { name: '仙桃市' },
          { name: '咸阳市' },
          { name: '孝感市' },
          { name: '西城区' },
        ],
      },
      {
        alpha: 'Y',
        subItems: [
          { name: '雅安市' },
          { name: '延安市' },
          { name: '延边朝鲜族自治州' },
          { name: '盐城市' },
          { name: '阳江市' },
          { name: '杨浦区' },
          { name: '阳泉市' },
          { name: '扬州市' },
          { name: '延庆区' },
          { name: '烟台市' },
          { name: '宜宾市' },
          { name: '宜昌市' },
        ],
      },
      {
        alpha: 'Z',
        subItems: [{ name: '枣庄市' }, { name: '彰化县' }, { name: '张家界市' }],
      },
    ],
  },
  onChoose(data) {
    console.log(data)
  },
})
